"""Add alliance configuration fields

Revision ID: 0aeb425f2f02
Revises: dd3ab3aacc59
Create Date: 2025-08-02 15:34:27.325277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aeb425f2f02'
down_revision = 'dd3ab3aacc59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scouting_alliance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_config_team', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pit_config_team', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('config_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('shared_game_config', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('shared_pit_config', sa.Text(), nullable=True))
        batch_op.drop_column('primary_team_config')
        batch_op.drop_column('shared_config')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scouting_alliance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared_config', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('primary_team_config', sa.INTEGER(), nullable=True))
        batch_op.drop_column('shared_pit_config')
        batch_op.drop_column('shared_game_config')
        batch_op.drop_column('config_status')
        batch_op.drop_column('pit_config_team')
        batch_op.drop_column('game_config_team')

    # ### end Alembic commands ###
