"""Add background_image to StrategyDrawing

Revision ID: 210419515cc2
Revises: 35fba2c73d42
Create Date: 2025-07-22 19:21:22.084879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '210419515cc2'
down_revision = '35fba2c73d42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy_drawing', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('background_image', sa.String(length=256), nullable=True))
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy_drawing', schema=None) as batch_op:
        batch_op.drop_column('background_image')

    # ### end Alembic commands ###
