"""Add scouting_team_number to relevant models for multi-tenancy

Revision ID: 312620ebe819
Revises: 210419515cc2
Create Date: 2025-07-31 00:20:57.617536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '312620ebe819'
down_revision = '210419515cc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scouting_team_number', sa.Integer(), nullable=True))

    with op.batch_alter_table('alliance_selection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scouting_team_number', sa.Integer(), nullable=True))

    with op.batch_alter_table('pit_scouting_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scouting_team_number', sa.Integer(), nullable=True))

    with op.batch_alter_table('scouting_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scouting_team_number', sa.Integer(), nullable=True))

    with op.batch_alter_table('strategy_drawing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scouting_team_number', sa.Integer(), nullable=True))

    with op.batch_alter_table('team_list_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scouting_team_number', sa.Integer(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scouting_team_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('scouting_team_number')

    with op.batch_alter_table('team_list_entry', schema=None) as batch_op:
        batch_op.drop_column('scouting_team_number')

    with op.batch_alter_table('strategy_drawing', schema=None) as batch_op:
        batch_op.drop_column('scouting_team_number')

    with op.batch_alter_table('scouting_data', schema=None) as batch_op:
        batch_op.drop_column('scouting_team_number')

    with op.batch_alter_table('pit_scouting_data', schema=None) as batch_op:
        batch_op.drop_column('scouting_team_number')

    with op.batch_alter_table('alliance_selection', schema=None) as batch_op:
        batch_op.drop_column('scouting_team_number')

    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_column('scouting_team_number')

    # ### end Alembic commands ###
