"""Add SharedTeamRanks table for team ranking sharing

Revision ID: 8f0a126e6ef6
Revises: be3173217f8f
Create Date: 2025-08-03 17:26:06.270729

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '8f0a126e6ef6'
down_revision = 'be3173217f8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shared_link_share_token'))

    op.drop_table('shared_link')
    with op.batch_alter_table('shared_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shared_links_share_id'))

    op.drop_table('shared_links')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_links',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('share_id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('share_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('share_data', sqlite.JSON(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('is_password_protected', sa.BOOLEAN(), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('last_accessed', sa.DATETIME(), nullable=True),
    sa.Column('access_count', sa.INTEGER(), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shared_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shared_links_share_id'), ['share_id'], unique=1)

    op.create_table('shared_link',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('share_token', sa.VARCHAR(length=64), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('page_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('parameters', sa.TEXT(), nullable=False),
    sa.Column('created_by_user_id', sa.INTEGER(), nullable=False),
    sa.Column('created_by_team', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.Column('view_count', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shared_link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shared_link_share_token'), ['share_token'], unique=1)

    # ### end Alembic commands ###
