"""Add scouting_team_number to Team, Event, and Match models for full multi-tenancy

Revision ID: dd3ab3aacc59
Revises: a1b2c3d4e5f6
Create Date: 2025-08-01 08:24:37.739607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd3ab3aacc59'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scouting_team_number', sa.Integer(), nullable=True))
        # Remove the unique constraint on code since multiple teams can have same event code
        batch_op.drop_constraint('uq_event_code', type_='unique')

    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scouting_team_number', sa.Integer(), nullable=True))

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scouting_team_number', sa.Integer(), nullable=True))
        # Remove the unique constraint on team_number since multiple scouting teams can have same team numbers
        batch_op.drop_constraint('uq_team_team_number', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_team_team_number', ['team_number'])
        batch_op.drop_column('scouting_team_number')

    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_column('scouting_team_number')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_event_code', ['code'])
        batch_op.drop_column('scouting_team_number')
    # ### end Alembic commands ###
